# Generated by Django 5.1.3 on 2024-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "image",
                    models.ImageField(upload_to="news/details", verbose_name="Фото"),
                ),
                ("day", models.IntegerField(verbose_name="День")),
                ("month", models.CharField(max_length=155, verbose_name="Заголовка")),
            ],
            options={
                "verbose_name_plural": "Лист Новостей",
            },
        ),
    ]
