# Generated by Django 5.1.3 on 2024-12-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_newscomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newscomment",
            old_name="descriptions",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="newscomment",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="newscomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создание коментарий"
            ),
        ),
        migrations.AddField(
            model_name="newscomment",
            name="email",
            field=models.EmailField(
                default=1, max_length=254, verbose_name="Электронная почта"
            ),
            preserve_default=False,
        ),
    ]
