# Generated by Django 5.1.3 on 2024-12-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_rename_descriptions_newscomment_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newscomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Комментрия Новостей",
            },
        ),
        migrations.AlterField(
            model_name="newscomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-07-12", verbose_name="Дата создание коментарий"
            ),
            preserve_default=False,
        ),
    ]
