# Generated by Django 5.1.3 on 2024-12-11 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_alter_newscomment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscomment",
            name="news",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news.newslistdetails",
            ),
            preserve_default=False,
        ),
    ]
