# Generated by Django 5.1.3 on 2024-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                ("image", models.ImageField(upload_to="tour", verbose_name="Фото")),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "person",
                    models.CharField(max_length=155, verbose_name="Цена за человека"),
                ),
                (
                    "person_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Цена за человека"
                    ),
                ),
                (
                    "person_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Цена за человека"
                    ),
                ),
                ("star", models.CharField(max_length=50, verbose_name="Звезда")),
            ],
            options={
                "verbose_name_plural": "Лист Туров",
            },
        ),
    ]
