# Generated by Django 5.1.3 on 2024-12-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=155, verbose_name="Заголовка Туров"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Туров"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Туров"
                    ),
                ),
                ("image", models.ImageField(upload_to="tour", verbose_name="Фото")),
                (
                    "main",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Главной страницы"
                    ),
                ),
                (
                    "main_ru",
                    models.CharField(
                        max_length=155,
                        null=True,
                        verbose_name="Заголовка Главной страницы",
                    ),
                ),
                (
                    "main_en",
                    models.CharField(
                        max_length=155,
                        null=True,
                        verbose_name="Заголовка Главной страницы",
                    ),
                ),
                ("tour", models.CharField(max_length=155, verbose_name="Туры")),
                (
                    "tour_ru",
                    models.CharField(max_length=155, null=True, verbose_name="Туры"),
                ),
                (
                    "tour_en",
                    models.CharField(max_length=155, null=True, verbose_name="Туры"),
                ),
            ],
            options={
                "verbose_name_plural": "Страница туров",
            },
        ),
    ]
