# Generated by Django 5.1.3 on 2024-12-10 12:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinationsDetailModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("title_price", models.IntegerField(verbose_name="Заголовка Цены")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destinations.destinationsmodels",
                        verbose_name="Направление",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Детально о наших направлениях",
            },
        ),
    ]
