# Generated by Django 5.1.3 on 2024-12-11 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0002_destinationsdetailmodels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destinationsdetailmodels",
            name="title_price",
        ),
    ]
