# Generated by Django 5.1.3 on 2024-12-11 07:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0003_remove_destinationsdetailmodels_title_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destinationsdetailmodels",
            name="descriptions",
        ),
        migrations.AddField(
            model_name="destinationsmodels",
            name="descriptions",
            field=ckeditor.fields.RichTextField(
                default=1, verbose_name="Описание В деталей"
            ),
            preserve_default=False,
        ),
    ]
