# Generated by Django 5.1.3 on 2024-12-12 16:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0005_destinationspynkt"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinationsdetailmodels",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="destinationsdetailmodels",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="destinationsmodels",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание В деталей"
            ),
        ),
        migrations.AddField(
            model_name="destinationsmodels",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание В деталей"
            ),
        ),
        migrations.AddField(
            model_name="destinationsmodels",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="destinationsmodels",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="destinationspynkt",
            name="descriptions_en",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="destinationspynkt",
            name="descriptions_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="destinationspynkt",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="destinationspynkt",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
    ]
