# Generated by Django 5.1.3 on 2024-12-09 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                ("image", models.ImageField(upload_to="about", verbose_name="Фото")),
                (
                    "title_tevily",
                    models.CharField(max_length=155, verbose_name="Заголовка tevily"),
                ),
                (
                    "title_tevily_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка tevily"
                    ),
                ),
                (
                    "title_tevily_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка tevily"
                    ),
                ),
                (
                    "title_tevily2",
                    models.CharField(max_length=155, verbose_name="Заголовка tevily 2"),
                ),
                (
                    "title_tevily2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка tevily 2"
                    ),
                ),
                (
                    "title_tevily2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка tevily 2"
                    ),
                ),
                (
                    "title_tevily3",
                    models.CharField(max_length=155, verbose_name="Заголовка tevily 3"),
                ),
                (
                    "title_tevily3_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка tevily 3"
                    ),
                ),
                (
                    "title_tevily3_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка tevily 3"
                    ),
                ),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание tevily"),
                ),
                (
                    "descriptions_ru",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Описание tevily"
                    ),
                ),
                (
                    "descriptions_en",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Описание tevily"
                    ),
                ),
                ("image2", models.ImageField(upload_to="about", verbose_name="Фото")),
                (
                    "title_ready",
                    models.CharField(max_length=155, verbose_name="Заголовка Готовый"),
                ),
                (
                    "title_ready_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Готовый"
                    ),
                ),
                (
                    "title_ready_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Готовый"
                    ),
                ),
                (
                    "title_ready2",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Готовый 2"
                    ),
                ),
                (
                    "title_ready2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Готовый 2"
                    ),
                ),
                (
                    "title_ready2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Готовый 2"
                    ),
                ),
                (
                    "title_saying",
                    models.CharField(max_length=155, verbose_name="Заголовка Говоря"),
                ),
                (
                    "title_saying_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Говоря"
                    ),
                ),
                (
                    "title_saying_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Говоря"
                    ),
                ),
                (
                    "title_saying2",
                    models.CharField(max_length=155, verbose_name="Заголовка Говоря 2"),
                ),
                (
                    "title_saying2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Говоря 2"
                    ),
                ),
                (
                    "title_saying2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Говоря 2"
                    ),
                ),
                (
                    "title_video",
                    models.CharField(max_length=155, verbose_name="Заголовка Видио"),
                ),
                (
                    "title_video_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Видио"
                    ),
                ),
                (
                    "title_video_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Видио"
                    ),
                ),
                (
                    "title_video2",
                    models.CharField(max_length=155, verbose_name="Заголовка Видио 2"),
                ),
                (
                    "title_video2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Видио 2"
                    ),
                ),
                (
                    "title_video2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Видио 2"
                    ),
                ),
                ("video", models.URLField(verbose_name="Ссылка на видео")),
                (
                    "title_team",
                    models.CharField(max_length=155, verbose_name="Заголовка команды"),
                ),
                (
                    "title_team_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка команды"
                    ),
                ),
                (
                    "title_team_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка команды"
                    ),
                ),
                (
                    "title_team2",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка команды 2"
                    ),
                ),
                (
                    "title_team2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка команды 2"
                    ),
                ),
                (
                    "title_team2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка команды 2"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Настройки Страницы О нас",
            },
        ),
        migrations.CreateModel(
            name="AboutPercent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("procent", models.IntegerField(verbose_name="Проценты")),
            ],
            options={
                "verbose_name_plural": "Проценты о нас ",
            },
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="contact", verbose_name="Фото на баннаре"
                    ),
                ),
                (
                    "title_form",
                    models.CharField(max_length=155, verbose_name="Заголовка Формы"),
                ),
                (
                    "title_form_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Формы"
                    ),
                ),
                (
                    "title_form_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Формы"
                    ),
                ),
                (
                    "title_form2",
                    models.CharField(max_length=155, verbose_name="Заголовка Формы 2"),
                ),
                (
                    "title_form2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Формы 2"
                    ),
                ),
                (
                    "title_form2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Формы 2"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Настройка Страницы Конатакты",
            },
        ),
        migrations.CreateModel(
            name="DopInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "descriptions_ru",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
                ),
                (
                    "descriptions_en",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            (
                                "Профессиональный и сертифицированный",
                                "Профессиональный и сертифицированный",
                            ),
                            (
                                "Получите мгновенное бронирование туров",
                                "Получите мгновенное бронирование туров",
                            ),
                        ],
                        max_length=155,
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Допольнительная Информация",
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name_plural": "Форма на страницах",
            },
        ),
        migrations.CreateModel(
            name="GalleryMainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                ("image", models.ImageField(upload_to="Фото")),
                (
                    "advantages_main_page",
                    models.CharField(max_length=155, verbose_name="Наши примущество"),
                ),
                (
                    "advantages_main_page_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Наши примущество"
                    ),
                ),
                (
                    "advantages_main_page_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Наши примущество"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Галлерия на Главной страницы",
            },
        ),
        migrations.CreateModel(
            name="ImageMainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Фото")),
            ],
            options={
                "verbose_name_plural": "Фото На Главной Странице",
            },
        ),
        migrations.CreateModel(
            name="MainTours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="main/tours/", verbose_name="Фото"),
                ),
                (
                    "superb",
                    models.CharField(max_length=155, verbose_name="превосходно"),
                ),
                (
                    "superb_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="превосходно"
                    ),
                ),
                (
                    "superb_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="превосходно"
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "name_city",
                    models.CharField(max_length=155, verbose_name="Название города"),
                ),
                (
                    "name_city_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Название города"
                    ),
                ),
                (
                    "name_city_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Название города"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Туры В Главной странице",
            },
        ),
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="partners/", verbose_name="Лого парнетров"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Наши Партнеры",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title2",
                    models.CharField(max_length=155, verbose_name="Заголовка - 2"),
                ),
                (
                    "title2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка - 2"
                    ),
                ),
                (
                    "title2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка - 2"
                    ),
                ),
                (
                    "title_plan_1",
                    models.CharField(max_length=155, verbose_name="Заголовка Плана"),
                ),
                (
                    "title_plan_1_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Плана"
                    ),
                ),
                (
                    "title_plan_1_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Плана"
                    ),
                ),
                (
                    "title_plan_2",
                    models.CharField(max_length=155, verbose_name="Заголовка Плана 2"),
                ),
                (
                    "title_plan_2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Плана 2"
                    ),
                ),
                (
                    "title_plan_2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Плана 2"
                    ),
                ),
                (
                    "descriptions_plan",
                    ckeditor.fields.RichTextField(verbose_name="Описание плана"),
                ),
                (
                    "descriptions_plan_ru",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Описание плана"
                    ),
                ),
                (
                    "descriptions_plan_en",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Описание плана"
                    ),
                ),
                (
                    "image_plan",
                    models.ImageField(
                        upload_to="settingsplan", verbose_name="Фото плана"
                    ),
                ),
                (
                    "title_tours",
                    models.CharField(max_length=155, verbose_name="Заголовка Туров"),
                ),
                (
                    "title_tours_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Туров"
                    ),
                ),
                (
                    "title_tours_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Туров"
                    ),
                ),
                (
                    "title_tours2",
                    models.CharField(max_length=155, verbose_name="Заголовка Туров 2"),
                ),
                (
                    "title_tours2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Туров 2"
                    ),
                ),
                (
                    "title_tours2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Туров 2"
                    ),
                ),
                (
                    "title_tevily",
                    models.CharField(max_length=155, verbose_name="Заголовка Тевили"),
                ),
                (
                    "title_tevily_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Тевили"
                    ),
                ),
                (
                    "title_tevily_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Тевили"
                    ),
                ),
                (
                    "title_tevily2",
                    models.CharField(max_length=155, verbose_name="Заголовка Тевили 2"),
                ),
                (
                    "title_tevily2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Тевили 2"
                    ),
                ),
                (
                    "title_tevily2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Тевили 2"
                    ),
                ),
                ("video_tevily", models.URLField(verbose_name="Ссылка на видео")),
                (
                    "title_partners",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Партнеров"
                    ),
                ),
                (
                    "title_partners_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Партнеров"
                    ),
                ),
                (
                    "title_partners_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Партнеров"
                    ),
                ),
                (
                    "title_testimonials",
                    models.CharField(max_length=155, verbose_name="Заголовка Отзывов"),
                ),
                (
                    "title_testimonials_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Отзывов"
                    ),
                ),
                (
                    "title_testimonials_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Отзывов"
                    ),
                ),
                (
                    "title_testimonials2",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Отзывов 2"
                    ),
                ),
                (
                    "title_testimonials2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Отзывов 2"
                    ),
                ),
                (
                    "title_testimonials2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Отзывов 2"
                    ),
                ),
                (
                    "title_choices",
                    models.CharField(max_length=155, verbose_name="Заголовка Выбора"),
                ),
                (
                    "title_choices_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Выбора"
                    ),
                ),
                (
                    "title_choices_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Выбора"
                    ),
                ),
                (
                    "title_choices2",
                    models.CharField(max_length=155, verbose_name="Заголовка Выбора 2"),
                ),
                (
                    "title_choices2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Выбора 2"
                    ),
                ),
                (
                    "title_choices2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Выбора 2"
                    ),
                ),
                (
                    "descriptions_choices",
                    ckeditor.fields.RichTextField(verbose_name="Описание выбора"),
                ),
                (
                    "descriptions_choices_ru",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Описание выбора"
                    ),
                ),
                (
                    "descriptions_choices_en",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Описание выбора"
                    ),
                ),
                (
                    "image_choices",
                    models.ImageField(upload_to="settings", verbose_name="Фото Выбора"),
                ),
                (
                    "title_news",
                    models.CharField(max_length=155, verbose_name="Заголовка Новостей"),
                ),
                (
                    "title_news_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Новостей"
                    ),
                ),
                (
                    "title_news_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Новостей"
                    ),
                ),
                (
                    "title_news2",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Новостей 2"
                    ),
                ),
                (
                    "title_news2_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Новостей 2"
                    ),
                ),
                (
                    "title_news2_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка Новостей 2"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Настройки Главной Страницы",
            },
        ),
        migrations.CreateModel(
            name="SettingsBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "descriptions_ru",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
                ),
                (
                    "descriptions_en",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
                ),
                ("image", models.ImageField(upload_to="settings", verbose_name="Фото")),
            ],
            options={
                "verbose_name_plural": "Настройка Главной страницы Баннера",
            },
        ),
        migrations.CreateModel(
            name="TeamAboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=155, verbose_name="Должность"),
                ),
                (
                    "job_title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "job_title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="team_about", verbose_name="Фото"),
                ),
                ("fb", models.URLField(blank=True, null=True, verbose_name="Facebook")),
                (
                    "inst",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="Твиттер"),
                ),
            ],
            options={
                "verbose_name_plural": "Наша команда (Страница О нас)",
            },
        ),
        migrations.CreateModel(
            name="VideoMainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=155, null=True, verbose_name="Заголовка"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Дикая природаТуры", "Дикая природаТуры"),
                            ("Парапланерные туры", "Парапланерные туры"),
                            ("Приключенческие туры", "Приключенческие туры"),
                            ("Дельтапланерные туры", "Дельтапланерные туры"),
                        ],
                        max_length=155,
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Видео на Главной странице",
            },
        ),
    ]
