# Generated by Django 5.1.3 on 2024-12-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutpercent",
            options={"verbose_name_plural": "Проценты (о нас )"},
        ),
        migrations.AddField(
            model_name="aboutpercent",
            name="title_en",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
        migrations.AddField(
            model_name="aboutpercent",
            name="title_ru",
            field=models.CharField(max_length=155, null=True, verbose_name="Заголовка"),
        ),
    ]
