# Generated by Django 5.1.3 on 2024-12-05 07:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_settingsbanner_alter_settings_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name_plural": "Настройки Главной Страницы"},
        ),
        migrations.AlterModelOptions(
            name="settingsbanner",
            options={"verbose_name_plural": "Настройка Главной страницы Баннера"},
        ),
        migrations.AddField(
            model_name="settings",
            name="descriptions_choices",
            field=ckeditor.fields.RichTextField(
                default=1, verbose_name="Описание выбора"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="image_choices",
            field=models.ImageField(
                default=1, upload_to="settings", verbose_name="Фото Выбора"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_choices",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Выбора"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_choices2",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Выбора 2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_news",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Новостей"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_news2",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Новостей 2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_partners",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Партнеров"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_testimonials",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Отзывов"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_testimonials2",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Отзывов 2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_tevily",
            field=models.CharField(
                default=11, max_length=155, verbose_name="Заголовка Тевили"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="title_tevily2",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Тевили 2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="video_tevily",
            field=models.URLField(default=11, verbose_name="Ссылка на видео"),
            preserve_default=False,
        ),
    ]
