# Generated by Django 5.1.3 on 2024-12-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "settings",
            "0003_alter_settings_options_alter_settingsbanner_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryMainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("image", models.ImageField(upload_to="Фото")),
            ],
            options={
                "verbose_name_plural": "Галлерия на Главной страницы",
            },
        ),
    ]
