# Generated by Django 5.1.3 on 2024-12-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_maintours"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Дикая природаТуры", "Дикая природаТуры"),
                            ("Парапланерные туры", "Парапланерные туры"),
                            ("Приключенческие туры", "Приключенческие туры"),
                            ("Дельтапланерные туры", "Дельтапланерные туры"),
                        ],
                        max_length=155,
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Видео на Главной странице",
            },
        ),
    ]
