# Generated by Django 5.1.3 on 2024-12-05 12:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0009_imagemainpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DopInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            (
                                "Профессиональный и сертифицированный",
                                "Профессиональный и сертифицированный",
                            ),
                            (
                                "Получите мгновенное бронирование туров",
                                "Получите мгновенное бронирование туров",
                            ),
                        ],
                        max_length=155,
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Допольнительная Информация",
            },
        ),
    ]
