# Generated by Django 5.1.3 on 2024-12-06 05:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0010_dopinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "title_tevily",
                    models.CharField(max_length=155, verbose_name="Заголовка tevily"),
                ),
                (
                    "title_tevily2",
                    models.CharField(max_length=155, verbose_name="Заголовка tevily 2"),
                ),
                (
                    "title_tevily3",
                    models.CharField(max_length=155, verbose_name="Заголовка tevily 3"),
                ),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание tevily"),
                ),
                ("image", models.ImageField(upload_to="about", verbose_name="Фото")),
                (
                    "title_ready",
                    models.CharField(max_length=155, verbose_name="Заголовка Готовый"),
                ),
                (
                    "title_ready2",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка Готовый 2"
                    ),
                ),
                (
                    "title_saying",
                    models.CharField(max_length=155, verbose_name="Заголовка Говоря"),
                ),
                (
                    "title_saying2",
                    models.CharField(max_length=155, verbose_name="Заголовка Говоря 2"),
                ),
                (
                    "title_video",
                    models.CharField(max_length=155, verbose_name="Заголовка Видио"),
                ),
                (
                    "title_video2",
                    models.CharField(max_length=155, verbose_name="Заголовка Видио 2"),
                ),
                ("video", models.URLField(verbose_name="Ссылка на видео")),
                (
                    "title_team",
                    models.CharField(max_length=155, verbose_name="Заголовка команды"),
                ),
                (
                    "title_team2",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка команды 2"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Настройки Страницы О нас",
            },
        ),
    ]
