# Generated by Django 5.1.3 on 2024-12-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0011_aboutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="image2",
            field=models.ImageField(default=1, upload_to="about", verbose_name="Фото"),
            preserve_default=False,
        ),
    ]
