# Generated by Django 5.1.3 on 2024-12-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0013_aboutpercent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "job_title",
                    models.CharField(max_length=155, verbose_name="Должность"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="team_about", verbose_name="Фото"),
                ),
                ("fb", models.URLField(blank=True, null=True, verbose_name="Facebook")),
                (
                    "inst",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                ("skype", models.URLField(blank=True, null=True, verbose_name="Скайп")),
            ],
            options={
                "verbose_name_plural": "Наша команда (Страница О нас)",
            },
        ),
    ]
