# Generated by Django 5.1.3 on 2024-12-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0014_teamaboutpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamaboutpage",
            name="skype",
        ),
        migrations.AddField(
            model_name="teamaboutpage",
            name="twitter",
            field=models.URLField(blank=True, null=True, verbose_name="Твиттер"),
        ),
    ]
