# Generated by Django 5.1.3 on 2024-12-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0015_remove_teamaboutpage_skype_teamaboutpage_twitter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "image",
                    models.ImageField(
                        upload_to="contact", verbose_name="Фото на баннаре"
                    ),
                ),
                (
                    "title_form",
                    models.CharField(max_length=155, verbose_name="Заголовка Формы"),
                ),
                (
                    "title_form2",
                    models.CharField(max_length=155, verbose_name="Заголовка Формы 2"),
                ),
            ],
            options={
                "verbose_name_plural": "Настройка Страницы Конатакты",
            },
        ),
    ]
